### ISSUE TITLE
Broken pipe

### ISSUE THREAD

**Issue by tiedyedguy** [faustocarrera/imgur-python#16]
Started about a week ago I get either "Broken Pipe" and "Connection reset by peer" on image_upload.  This script has run for years fine and this just started.

Here is full error:

``Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 357, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.6/http/client.py", line 1281, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1327, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1276, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1081, in _send_output
    self.send(chunk)
  File "/usr/lib/python3.6/http/client.py", line 1002, in send
    self.sock.sendall(data)
  File "/usr/lib/python3.6/ssl.py", line 975, in sendall
    v = self.send(byte_view[count:])
  File "/usr/lib/python3.6/ssl.py", line 944, in send
    return self._sslobj.write(data)
  File "/usr/lib/python3.6/ssl.py", line 642, in write
    return self._sslobj.write(data)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 367, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python3.6/dist-packages/six.py", line 702, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 357, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.6/http/client.py", line 1281, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1327, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1276, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1081, in _send_output
    self.send(chunk)
  File "/usr/lib/python3.6/http/client.py", line 1002, in send
    self.sock.sendall(data)
  File "/usr/lib/python3.6/ssl.py", line 975, in sendall
    v = self.send(byte_view[count:])
  File "/usr/lib/python3.6/ssl.py", line 944, in send
    return self._sslobj.write(data)
  File "/usr/lib/python3.6/ssl.py", line 642, in write
    return self._sslobj.write(data)
urllib3.exceptions.ProtocolError: ('Connection aborted.', BrokenPipeError(32, 'Broken pipe'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "myleftfoot.py", line 58, in <module>
    fileToUse, 'Untitled2', 'My2 first image upload')
  File "/usr/local/lib/python3.6/dist-packages/imgur_python/Imgur.py", line 254, in image_upload
    return self.image.upload(payload, files)
  File "/usr/local/lib/python3.6/dist-packages/imgur_python/Image.py", line 53, in upload
    files=files
  File "/usr/lib/python3/dist-packages/requests/api.py", line 112, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 520, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 630, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 490, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', BrokenPipeError(32, 'Broken pipe'))
``

**Comment by tiedyedguy** [comment]
It happens on my cloud based linux server and my local windows box.  Same error.

**Comment by tiedyedguy** [comment]
Also, I should add more context.  This script runs once a day in my mornings.  I would find it didn't run and would manually run it later in the day and it would work fine.  So I assumed it was just my cron messing up.  Today I finally set the cron job to log and found that error.  Then when I went to run the script manually I got the error over and over for an hour.

Then I posted this issue.

Then I ran the script one more time and it now worked.

lol.

**Comment by faustocarrera** [comment]
> Also, I should add more context. This script runs once a day in my mornings. I would find it didn't run and would manually run it later in the day and it would work fine. So I assumed it was just my cron messing up. Today I finally set the cron job to log and found that error. Then when I went to run the script manually I got the error over and over for an hour.
> 
> Then I posted this issue.
> 
> Then I ran the script one more time and it now worked.
> 
> lol.

How many files are you trying to upload and what is the total size of the files? Just to check if you working on the limits of the API

**Comment by tiedyedguy** [comment]
Just one jpg.  I preshrunk the files to under 9meg to avoid limit.

The file shouldn't be the issue also because the same file will work when it randomly works later.

**Comment by faustocarrera** [comment]
I will keep this thread as open while I investigate the issue, I'll keep you post and thanks for reporting it.

**Comment by tiedyedguy** [comment]
Of course it is a horrible one to diagnose and I apologize.   Today the script ran with no errors.

I wonder if it is just imgur api being stupid.

**Comment by tiedyedguy** [comment]
So, from the 20th to 24th, it ran no errors, first time.

This morning, error.

**Comment by faustocarrera** [comment]
> So, from the 20th to 24th, it ran no errors, first time.
> 
> This morning, error.

Seems to be a problem on their side, but I had no issues posting 3 times per day.

**Comment by faustocarrera** [comment]
Possible connectivity problem, no problem at all publishing more than 30 times a day using a test account
